### ISSUE TITLE
Producer startup failling

### ISSUE THREAD

**Issue by mobilars** [okteto/kafka-stack#3]
I'm getting the following error message when deploying the image in okteto:

2022-04-22 07:49:19.00 UTCproducer-7c9bb8795d-xdmv7[pod-event]Successfully pulled image "registry.cloud.okteto.net/mobilars/kafka-producer@sha256:648fb232acc41b6a129a3a819b5f385b8e2e6658a75c3f42b45587c3d7a669a8" in 22.171505847s
2022-04-22 07:49:24.00 UTCproducer-7c9bb8795d-xdmv7[pod-event]Created container producer
2022-04-22 07:49:24.00 UTCproducer-7c9bb8795d-xdmv7[pod-event]Started container producer
2022-04-22 07:49:24.52 UTCproducer-7c9bb8795d-xdmv7producerTraceback (most recent call last):
2022-04-22 07:49:24.52 UTCproducer-7c9bb8795d-xdmv7producer File "/usr/src/app/app.py", line 1, in <module>
2022-04-22 07:49:24.52 UTCproducer-7c9bb8795d-xdmv7producer from flask import Flask, request, jsonify
2022-04-22 07:49:24.52 UTCproducer-7c9bb8795d-xdmv7producer File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
2022-04-22 07:49:24.52 UTCproducer-7c9bb8795d-xdmv7producer from jinja2 import escape
2022-04-22 07:49:24.52 UTCproducer-7c9bb8795d-xdmv7producerImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.10/site-packages/jinja2/__init__.py)

**Comment by mobilars** [comment]
I guess this might be the issue: https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2

**Comment by rberrelleza** [comment]
> I guess this might be the issue: https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2

you were right, issue is now fixed!
